# Project: Acllib_test
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o acllib.o $(RES)
LINKOBJ  = main.o acllib.o $(RES)
LIBS =  -L"H:/Dev-Cpp/lib" -mwindows H:/Dev-Cpp/lib/libwinmm.a H:/Dev-Cpp/lib/libmsimg32.a H:/Dev-Cpp/lib/libkernel32.a H:/Dev-Cpp/lib/libuser32.a H:/Dev-Cpp/lib/libgdi32.a H:/Dev-Cpp/lib/libole32.a H:/Dev-Cpp/lib/liboleaut32.a H:/Dev-Cpp/lib/libuuid.a  
INCS =  -I"H:/Dev-Cpp/include" 
CXXINCS =  -I"H:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"H:/Dev-Cpp/include/c++/3.4.2/backward"  -I"H:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"H:/Dev-Cpp/include/c++/3.4.2"  -I"H:/Dev-Cpp/include" 
BIN  = Acllib_test.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Acllib_test.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Acllib_test.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
